### 判断一个矩阵是不是SO(3)

因为SO(3)空间满足：$R*R^T=I$，通过判断一个矩阵与SO(3)的距离来判断：

$$
D=||RR^T-I||_F
$$

In [1]:
# import ipynb_importer
import import_ipynb
import chapter_3
import numpy as np

def DistanceToSO3(mat):
    """Returns the Frobenius norm to describe the distance of mat from the
    SO(3) manifold

    :param mat: A 3x3 matrix
    :return: A quantity describing the distance of mat from the SO(3)
             manifold
    Computes the distance from mat to the SO(3) manifold using the following
    method:
    If det(mat) <= 0, return a large number.
    If det(mat) > 0, return norm(mat^T.mat - I).

    Example Input:
        mat = np.array([[ 1.0,  0.0,   0.0 ],
                        [ 0.0,  0.1,  -0.95],
                        [ 0.0,  1.0,   0.1 ]])
    Output:
        0.08835
    """
    if np.linalg.det(mat) > 0: # SO(3)流形行列式肯定>0
        return np.linalg.norm(np.dot(np.array(mat).T, mat) - np.eye(3)) # 返回RR^T-I的F范数
    else:
        return 1e+9 # 行列式<0则直接返回一个大数


def TestIfSO3(mat):
    """Returns true if mat is close to or on the manifold SO(3)

    :param mat: A 3x3 matrix
    :return: True if mat is very close to or in SO(3), false otherwise
    Computes the distance d from mat to the SO(3) manifold using the
    following method:
    If det(mat) <= 0, d = a large number.
    If det(mat) > 0, d = norm(mat^T.mat - I).
    If d is close to zero, return true. Otherwise, return false.

    Example Input:
        mat = np.array([[1.0, 0.0,  0.0 ],
                        [0.0, 0.1, -0.95],
                        [0.0, 1.0,  0.1 ]])
    Output:
        False
    """
    return abs(DistanceToSO3(mat)) < 1e-3 # 若小于1e-3则认为是SO(3)

importing Jupyter notebook from chapter_3.ipynb
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[6.123234e-17 1.000000e+00 0.000000e+00]
[[ 0 -3  2]
 [ 3  0 -1]
 [-2  1  0]]
[1 2 3]
[[ 1.00000000e+00 -6.83580866e-17  0.00000000e+00]
 [-6.83580866e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 1.00000000e+00  4.26642159e-17  1.22133484e-17]
 [ 4.26642159e-17  1.00000000e+00 -3.52068201e-17]
 [ 1.22133484e-17 -3.52068201e-17  1.00000000e+00]]
Axis Angle: 
  (array([0.40824829, 0.81649658, 0.40824829]), 2.449489742783178)
so3mat:
  [[ 0 -1  2]
 [ 1  0 -1]
 [-2  1  0]]
MatrixExp3：
 [[-0.47492144  0.32944181  0.81603782]
 [ 0.85049534  0.41003142  0.32944181]
 [-0.22606924  0.85049534 -0.47492144]]
MatrixLog3:
 [[ 0. -1.  2.]
 [ 1.  0. -1.]
 [-2.  1.  0.]]
so3 vec:  [1. 2. 1.]
Axis Angle: 
  (array([0.40824829, 0.81649658, 0.40824829]), 2.4494897427831814)
[ 0  0  2 -2 -4  0]
[ 0.  0.  2. -2. -4.  0.]
[ 0.   0.  -2.   2.8  4.   0. ]
[ 0.   0.  -2.   2.8  4.

验证一下：

In [3]:
mat = np.array([[1.0, 0.0,  0.0 ],
                [0.0, 0.1, -0.95],
                [0.0, 1.0,  0.1 ]])

print(TestIfSO3(mat))

A = chapter_3.Rodrigues(chapter_3.Normalize([1, 1, 0]), 90.0/180.0*np.pi)

print(TestIfSO3(A))

False
True
